#!/usr/bin/env bash

function chords() {
    ls chords/
}

function pick() {
    chords | sort -R | head -n 1
}

function minor() {
    chords | grep 'm.wav$'
}

function major() {
    chords | grep -v 'm.wav$'
}

function main() {
    local group_1=$(major)
    local group_2=$(minor)
    local right=0
    local wrong=0

    clear
    printf "Right: $right\nWrong: $wrong\n\n"
    printf "Group 1:\n\t$(echo "$group_1" | sed 's/.wav//g' | tr '\n' ' ')\n\n"
    printf "Group 2:\n\t$(echo "$group_2" | sed 's/.wav//g' | tr '\n' ' ')\n\n"

    while :; do
        chord=$(pick)
        printf '\r\033[K'
        printf "To which group does this sound belong? "
        afplay "chords/$chord"

        read -n 1 answer
        [[ "$answer" == "q" ]] && break
        answer="group_$answer"

        if [[ -z "$(echo "${!answer}" | grep $chord)" ]]; then
            prefix="Wrong answer"
            wrong=$(echo "$wrong + 1" | bc)
        else
            prefix="Right answer"
            right=$(echo "$right + 1" | bc)
        fi
        total=$(echo "$right + $wrong" | bc)
        percentage="$(echo "scale=2; $right/$total" | bc | sed 's/\.//g')%%"

        echo $percentage

        clear
        printf "Right: $right\nWrong: $wrong\nRate: $percentage\n\n"
        printf "Group 1:\n\t$(echo "$group_1" | sed 's/.wav//g' | tr '\n' ' ')\n\n"
        printf "Group 2:\n\t$(echo "$group_2" | sed 's/.wav//g' | tr '\n' ' ')\n\n"
        printf "$prefix, this chord was $(echo $chord | sed 's/.wav//g')"

        read -s -n 1 key
        [[ "$key" == "q" ]] && break
    done
    echo ""
}

main